"""add app analytics tables

Revision ID: acc5085799a1
Revises: 1402f6657400
Create Date: 2026-08-29 21:14:47.054237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# TimestampMixin renders as app.db.base.UTCDateTime; autogenerate emits the
# fully-qualified name without importing it.
import app.db.base


# revision identifiers, used by Alembic.
revision: str = 'acc5085799a1'
down_revision: Union[str, None] = '1402f6657400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_analytics_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('report_kind', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('territory', sa.String(length=8), nullable=False),
    sa.Column('source_type', sa.String(length=128), nullable=False),
    sa.Column('page_type', sa.String(length=64), nullable=False),
    sa.Column('page_title', sa.String(length=255), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=False),
    sa.Column('app_version', sa.String(length=64), nullable=False),
    sa.Column('dim_hash', sa.String(length=64), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('unique_impressions', sa.Integer(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('unique_page_views', sa.Integer(), nullable=False),
    sa.Column('taps', sa.Integer(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('redownloads', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credential_id'], ['asc_credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'report_kind', 'date', 'dim_hash', name='uq_app_analytics_daily_grain')
    )
    op.create_index('ix_app_analytics_daily_app_date', 'app_analytics_daily', ['app_id', 'date'], unique=False)
    op.create_index(op.f('ix_app_analytics_daily_app_id'), 'app_analytics_daily', ['app_id'], unique=False)
    op.create_index(op.f('ix_app_analytics_daily_credential_id'), 'app_analytics_daily', ['credential_id'], unique=False)
    op.create_table('app_analytics_report_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.String(length=24), nullable=False),
    sa.Column('asc_request_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('last_synced_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'access_type', name='uq_app_analytics_request_app_access')
    )
    op.create_index(op.f('ix_app_analytics_report_requests_app_id'), 'app_analytics_report_requests', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_analytics_report_requests_app_id'), table_name='app_analytics_report_requests')
    op.drop_table('app_analytics_report_requests')
    op.drop_index(op.f('ix_app_analytics_daily_credential_id'), table_name='app_analytics_daily')
    op.drop_index(op.f('ix_app_analytics_daily_app_id'), table_name='app_analytics_daily')
    op.drop_index('ix_app_analytics_daily_app_date', table_name='app_analytics_daily')
    op.drop_table('app_analytics_daily')
    # ### end Alembic commands ###
